<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.22.2" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventHorizon.Application\EventHorizon.Application.csproj" />
    <ProjectReference Include="..\EventHorizon.Domain\EventHorizon.Domain.csproj" />
  </ItemGroup>

</Project>
